# Este arquivo foi migrado para usar Azure Key Vault
# Use os seguintes arquivos em vez deste:
# - 01-secret-provider-class.yaml (configura acesso ao Key Vault)
# - 02-order-api-deployment.yaml (deployment com volumes do Key Vault)
# - 03-service-account.yaml (service account com workload identity)

# Para aplicar a configuração completa:
# kubectl apply -f 01-secret-provider-class.yaml
# kubectl apply -f 03-service-account.yaml  
# kubectl apply -f 02-order-api-deployment.yaml

apiVersion: v1
kind: Secret
metadata:
  name: fasttechfoods-order-api-secrets
  namespace: fasttechfoods
  annotations:
    # Este secret será criado automaticamente pelo CSI Secret Store Driver
    # baseado nos valores do Azure Key Vault kv-hackathon
    managed-by: "secrets-store-csi-driver"
type: Opaque
data:
  # Os valores serão populados automaticamente do Key Vault:
  # - SEC-CONNECTION-STRING-DATABASE -> CONNECTION_STRING_DATABASE
  # - SEC-JWT-SECRET -> JWT_SECRET  
  # - SEC-RABBITMQ-CONNECTION-STRING -> RABBITMQ_CONNECTION_STRING 
