apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent-loadbalancer
  namespace: fasttechfoods
  labels:
    app: zabbix-agent
spec:
  type: LoadBalancer
  selector:
    app: zabbix-agent
  ports:
  - port: 10050
    targetPort: 10050
    protocol: TCP
    name: zabbix-agent
  loadBalancerSourceRanges:
  - "20.220.170.26/32"  # Permitir apenas o servidor Zabbix
